# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
